# Generated by Django 5.0.4 on 2024-04-21 23:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_immobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmobileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images", verbose_name="Images")),
                (
                    "immobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immobile_images",
                        to="myapp.immobile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_start", models.DateTimeField(verbose_name="Inicio")),
                ("dt_end", models.DateTimeField(verbose_name="Fim")),
                (
                    "create_ad",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.client"
                    ),
                ),
                (
                    "immobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reg_location",
                        to="myapp.immobile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registrar Locação",
                "verbose_name_plural": "Registrar Locação",
                "ordering": ["-id"],
            },
        ),
    ]
