# Generated by Django 5.0.4 on 2024-04-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_immobileimage_registerlocation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registerlocation",
            old_name="create_ad",
            new_name="create_at",
        ),
    ]
